export type AdminField = { key: string; label: string; type?: "text" | "textarea" | "url" | "email" | "number" | "checkbox" | "image" | "select"; required?: boolean; defaultValue?: string | boolean | number };
export type AdminResource = { label: string; singular: string; fields: AdminField[]; singleton?: boolean };

export const adminResources: Record<string, AdminResource> = {
  about: { label: "About sections", singular: "section", fields: [{ key: "title", label: "Title", required: true }, { key: "content", label: "Content", type: "textarea", required: true }, { key: "order", label: "Display order", type: "number", defaultValue: 0 }, { key: "isVisible", label: "Visible on portfolio", type: "checkbox", defaultValue: true }] },
  contact: { label: "Contact profile", singular: "profile", singleton: true, fields: [
    { key: "name", label: "First name", required: true }, { key: "lastname", label: "Last name" }, { key: "title", label: "Professional title" }, { key: "summary", label: "Summary", type: "textarea" }, { key: "image", label: "Portrait", type: "image" }, { key: "email", label: "Email", type: "email" }, { key: "phone", label: "Phone" }, { key: "location", label: "Location" }, { key: "github", label: "GitHub URL", type: "url" }, { key: "linkedin", label: "LinkedIn URL", type: "url" }, { key: "website", label: "Website URL", type: "url" },
  ] },
  education: { label: "Education", singular: "education record", singleton: true, fields: [{ key: "certificate", label: "Certificate", required: true }, { key: "institute", label: "Institute", required: true }, { key: "date", label: "Date" }, { key: "location", label: "Location" }] },
  experiences: { label: "Experience", singular: "experience", fields: [{ key: "name", label: "Company", required: true }, { key: "position", label: "Position", required: true }, { key: "date", label: "Date" }, { key: "description", label: "Description", type: "textarea" }, { key: "image", label: "Company image", type: "image" }, { key: "showInCV", label: "Show in CV", type: "checkbox" }, { key: "order", label: "Display order", type: "number", defaultValue: 0 }, { key: "isVisible", label: "Visible on portfolio", type: "checkbox", defaultValue: true }] },
  skills: { label: "Skills", singular: "skill", fields: [{ key: "name", label: "Name", required: true }, { key: "level", label: "Level" }, { key: "type", label: "Skill type", type: "select", required: true }, { key: "order", label: "Display order", type: "number", defaultValue: 0 }, { key: "isVisible", label: "Visible on portfolio", type: "checkbox", defaultValue: true }] },
  settings: { label: "Site settings", singular: "settings", singleton: true, fields: [
    { key: "siteTitle", label: "SEO title", required: true }, { key: "siteDescription", label: "SEO description", type: "textarea", required: true },
    { key: "heroEyebrow", label: "Hero eyebrow" }, { key: "heroCtaLabel", label: "Hero button label" }, { key: "heroCtaHref", label: "Hero button destination" }, { key: "portraitLabelPrefix", label: "Portrait location prefix" },
    { key: "navAboutLabel", label: "Navigation: About" }, { key: "navExperienceLabel", label: "Navigation: Experience" }, { key: "navWorkLabel", label: "Navigation: Work" }, { key: "navSkillsLabel", label: "Navigation: Skills" }, { key: "navContactLabel", label: "Navigation: Contact" }, { key: "navCvLabel", label: "Navigation: CV" },
    { key: "experienceKicker", label: "Experience kicker" }, { key: "experienceTitle", label: "Experience heading" }, { key: "workKicker", label: "Work kicker" }, { key: "workTitle", label: "Work heading" }, { key: "skillsKicker", label: "Skills kicker" }, { key: "skillsTitle", label: "Skills heading" },
    { key: "contactKicker", label: "Contact kicker" }, { key: "contactTitle", label: "Contact heading" }, { key: "contactFallbackText", label: "Contact fallback summary", type: "textarea" },
    { key: "formNameLabel", label: "Form: Name label" }, { key: "formEmailLabel", label: "Form: Email label" }, { key: "formSubjectLabel", label: "Form: Subject label" }, { key: "formMessageLabel", label: "Form: Message label" }, { key: "formSubmitLabel", label: "Form: Submit label" }, { key: "formSendingLabel", label: "Form: Sending label" }, { key: "formSuccessTitle", label: "Form: Success title" }, { key: "formSuccessMessage", label: "Form: Success message" }, { key: "formErrorTitle", label: "Form: Error title" }, { key: "formErrorMessage", label: "Form: Error fallback" },
    { key: "cvKicker", label: "CV kicker" }, { key: "cvTitle", label: "CV heading" }, { key: "cvContactHeading", label: "CV: Contact heading" }, { key: "cvEducationHeading", label: "CV: Education heading" }, { key: "cvLinksHeading", label: "CV: Links heading" }, { key: "cvExperienceHeading", label: "CV: Experience heading" }, { key: "cvProjectsHeading", label: "CV: Projects heading" }, { key: "cvSkillsHeading", label: "CV: Skills heading" }, { key: "cvDownloadLabel", label: "CV download label" }, { key: "footerText", label: "Footer credit" },
    { key: "showExperience", label: "Show experience section", type: "checkbox", defaultValue: true }, { key: "showWork", label: "Show work section", type: "checkbox", defaultValue: true }, { key: "showSkills", label: "Show skills section", type: "checkbox", defaultValue: true }, { key: "showContact", label: "Show contact section", type: "checkbox", defaultValue: true }, { key: "showCv", label: "Show CV section", type: "checkbox", defaultValue: true },
  ] },
  types: { label: "Skill types", singular: "skill type", fields: [{ key: "name", label: "Name", required: true }, { key: "order", label: "Display order", type: "number", defaultValue: 0 }, { key: "isVisible", label: "Visible on portfolio", type: "checkbox", defaultValue: true }] },
  work: { label: "Projects", singular: "project", fields: [{ key: "name", label: "Name", required: true }, { key: "description", label: "Description", type: "textarea" }, { key: "technologies", label: "Technologies" }, { key: "link", label: "Project URL", type: "url" }, { key: "image", label: "Project image", type: "image" }, { key: "showInCV", label: "Show in CV", type: "checkbox" }, { key: "order", label: "Display order", type: "number", defaultValue: 0 }, { key: "isVisible", label: "Visible on portfolio", type: "checkbox", defaultValue: true }] },
};
