export type AdminField = { key: string; label: string; type?: "text" | "textarea" | "url" | "email" | "number" | "checkbox" | "image" | "pdf" | "select"; required?: boolean; defaultValue?: string | boolean | number; options?: { label: string; value: string }[] };
export type AdminResource = { label: string; singular: string; fields: AdminField[]; singleton?: boolean };

export const adminResources: Record<string, AdminResource> = {
  about: { label: "About sections", singular: "section", fields: [{ key: "title", label: "Title", required: true }, { key: "content", label: "Content", type: "textarea", required: true }, { key: "order", label: "Display order", type: "number", defaultValue: 0 }, { key: "isVisible", label: "Visible on portfolio", type: "checkbox", defaultValue: true }] },
  contact: { label: "Contact profile", singular: "profile", singleton: true, fields: [
    { key: "name", label: "First name", required: true }, { key: "lastname", label: "Last name" }, { key: "title", label: "Professional title" }, { key: "summary", label: "Summary", type: "textarea" }, { key: "image", label: "Portrait", type: "image" }, { key: "cv", label: "CV document (PDF)", type: "pdf" }, { key: "email", label: "Email", type: "email" }, { key: "phone", label: "Phone" }, { key: "location", label: "Location" }, { key: "linkedin", label: "LinkedIn URL", type: "url" }, { key: "x", label: "X URL", type: "url" }, { key: "facebook", label: "Facebook URL", type: "url" }, { key: "website", label: "Website URL", type: "url" },
  ] },
  education: { label: "Education", singular: "education record", fields: [{ key: "certificate", label: "Degree or certificate", required: true }, { key: "institute", label: "Institution", required: true }, { key: "date", label: "Date" }, { key: "location", label: "Location" }, { key: "order", label: "Display order", type: "number", defaultValue: 0 }, { key: "isVisible", label: "Visible on portfolio", type: "checkbox", defaultValue: true }] },
  experiences: { label: "Experience", singular: "experience", fields: [{ key: "name", label: "Company or client", required: true }, { key: "position", label: "Position or role", required: true }, { key: "date", label: "Date" }, { key: "location", label: "Location" }, { key: "category", label: "Category", type: "select", defaultValue: "Professional", options: [{ label: "Professional", value: "Professional" }, { label: "Freelance", value: "Freelance" }] }, { key: "description", label: "Description", type: "textarea" }, { key: "image", label: "Company image", type: "image" }, { key: "showInCV", label: "Show in CV", type: "checkbox" }, { key: "order", label: "Display order", type: "number", defaultValue: 0 }, { key: "isVisible", label: "Visible on portfolio", type: "checkbox", defaultValue: true }] },
  languages: { label: "Languages", singular: "language", fields: [{ key: "name", label: "Language", required: true }, { key: "level", label: "Proficiency", required: true }, { key: "order", label: "Display order", type: "number", defaultValue: 0 }, { key: "isVisible", label: "Visible on portfolio", type: "checkbox", defaultValue: true }] },
  skills: { label: "Skills", singular: "skill", fields: [{ key: "name", label: "Name", required: true }, { key: "level", label: "Level" }, { key: "type", label: "Skill type", type: "select", required: true }, { key: "order", label: "Display order", type: "number", defaultValue: 0 }, { key: "isVisible", label: "Visible on portfolio", type: "checkbox", defaultValue: true }] },
  settings: { label: "Site settings", singular: "settings", singleton: true, fields: [
    { key: "siteTitle", label: "SEO title", required: true }, { key: "siteDescription", label: "SEO description", type: "textarea", required: true },
    { key: "heroEyebrow", label: "Hero eyebrow" }, { key: "heroCtaLabel", label: "Hero button label" }, { key: "heroCtaHref", label: "Hero button destination" }, { key: "portraitLabelPrefix", label: "Portrait location prefix" },
    { key: "navAboutLabel", label: "Navigation: About" }, { key: "navExperienceLabel", label: "Navigation: Experience" }, { key: "navEducationLabel", label: "Navigation: Education" }, { key: "navWorkLabel", label: "Navigation: Work" }, { key: "navSkillsLabel", label: "Navigation: Skills" }, { key: "navLanguagesLabel", label: "Navigation: Languages" }, { key: "navContactLabel", label: "Navigation: Contact" }, { key: "navCvLabel", label: "Navigation: CV" },
    { key: "experienceKicker", label: "Experience kicker" }, { key: "experienceTitle", label: "Experience heading" }, { key: "educationKicker", label: "Education kicker" }, { key: "educationTitle", label: "Education heading" }, { key: "educationDegreesHeading", label: "Academic education heading" }, { key: "educationTrainingHeading", label: "Professional training heading" }, { key: "workKicker", label: "Work kicker" }, { key: "workTitle", label: "Work heading" }, { key: "skillsKicker", label: "Skills kicker" }, { key: "skillsTitle", label: "Skills heading" }, { key: "languagesKicker", label: "Languages kicker" }, { key: "languagesTitle", label: "Languages heading" },
    { key: "contactKicker", label: "Contact kicker" }, { key: "contactTitle", label: "Contact heading" }, { key: "contactFallbackText", label: "Contact fallback summary", type: "textarea" },
    { key: "formNameLabel", label: "Form: Name label" }, { key: "formEmailLabel", label: "Form: Email label" }, { key: "formSubjectLabel", label: "Form: Subject label" }, { key: "formMessageLabel", label: "Form: Message label" }, { key: "formSubmitLabel", label: "Form: Submit label" }, { key: "formSendingLabel", label: "Form: Sending label" }, { key: "formSuccessTitle", label: "Form: Success title" }, { key: "formSuccessMessage", label: "Form: Success message" }, { key: "formErrorTitle", label: "Form: Error title" }, { key: "formErrorMessage", label: "Form: Error fallback" },
    { key: "cvKicker", label: "CV kicker" }, { key: "cvTitle", label: "CV heading" }, { key: "cvContactHeading", label: "CV: Contact heading" }, { key: "cvEducationHeading", label: "CV: Education heading" }, { key: "cvLinksHeading", label: "CV: Links heading" }, { key: "cvExperienceHeading", label: "CV: Experience heading" }, { key: "cvProjectsHeading", label: "CV: Projects heading" }, { key: "cvSkillsHeading", label: "CV: Skills heading" }, { key: "cvDownloadLabel", label: "CV download label" }, { key: "footerText", label: "Footer credit" },
    { key: "showExperience", label: "Show experience section", type: "checkbox", defaultValue: true }, { key: "showEducation", label: "Show education and training section", type: "checkbox", defaultValue: true }, { key: "showWork", label: "Show work section", type: "checkbox", defaultValue: true }, { key: "showSkills", label: "Show skills section", type: "checkbox", defaultValue: true }, { key: "showLanguages", label: "Show languages section", type: "checkbox", defaultValue: true }, { key: "showContact", label: "Show contact section", type: "checkbox", defaultValue: true }, { key: "showCv", label: "Show CV section", type: "checkbox", defaultValue: true },
  ] },
  training: { label: "Training", singular: "training record", fields: [{ key: "title", label: "Course or training title", required: true }, { key: "provider", label: "Provider", required: true }, { key: "date", label: "Date" }, { key: "location", label: "Location" }, { key: "order", label: "Display order", type: "number", defaultValue: 0 }, { key: "isVisible", label: "Visible on portfolio", type: "checkbox", defaultValue: true }] },
  types: { label: "Skill types", singular: "skill type", fields: [{ key: "name", label: "Name", required: true }, { key: "order", label: "Display order", type: "number", defaultValue: 0 }, { key: "isVisible", label: "Visible on portfolio", type: "checkbox", defaultValue: true }] },
  work: { label: "Selected work", singular: "work item", fields: [
    { key: "title", label: "Title", required: true },
    { key: "format", label: "Format", required: true },
    { key: "outlet", label: "Outlet or client" },
    { key: "role", label: "Role" },
    { key: "date", label: "Publication date" },
    { key: "topic", label: "Topic or category" },
    { key: "description", label: "Description", type: "textarea" },
    { key: "link", label: "Watch or read URL", type: "url" },
    { key: "image", label: "Thumbnail", type: "image" },
    { key: "isFeatured", label: "Featured work", type: "checkbox" },
    { key: "order", label: "Display order", type: "number", defaultValue: 0 },
    { key: "isVisible", label: "Visible on portfolio", type: "checkbox", defaultValue: true },
  ] },
};
