export type About = { _id: string; title: string; content: string; order?: number; isVisible?: boolean };
export type Experience = {
  _id: string;
  name: string;
  position: string;
  date: string;
  location: string;
  category: string;
  description: string;
  image?: string;
  showInCV?: boolean;
  order?: number;
  isVisible?: boolean;
};
export type Work = {
  _id: string;
  title: string;
  format: string;
  outlet: string;
  role: string;
  date: string;
  topic: string;
  description: string;
  image?: string;
  link?: string;
  isFeatured?: boolean;
  order?: number;
  isVisible?: boolean;
};
export type Skill = { _id: string; name: string; level: string; type: string; order?: number; isVisible?: boolean };
export type SkillType = { _id: string; name: string; skills: Skill[]; order?: number; isVisible?: boolean };
export type Language = { _id: string; name: string; level: string; order?: number; isVisible?: boolean };
export type Contact = {
  _id: string;
  name: string;
  lastname: string;
  title: string;
  summary: string;
  email: string;
  phone: string;
  location: string;
  linkedin?: string;
  x?: string;
  facebook?: string;
  website?: string;
  image?: string;
  cv?: string;
};
export type Education = {
  _id: string;
  certificate: string;
  institute: string;
  date: string;
  location: string;
  order?: number;
  isVisible?: boolean;
};
export type Training = { _id: string; title: string; provider: string; date: string; location: string; order?: number; isVisible?: boolean };
